# Generated by Django 4.2.4 on 2024-03-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='news/')),
            ],
        ),
        migrations.CreateModel(
            name='Streams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('authors', models.CharField(max_length=50)),
                ('licence', models.CharField(max_length=50)),
                ('studio', models.CharField(max_length=50)),
                ('kind', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('synopsys', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('episode', models.CharField(max_length=50)),
                ('banner', models.ImageField(upload_to='images/')),
                ('video', models.ImageField(upload_to='videos/')),
                ('poster', models.ImageField(upload_to='images/')),
                ('season', models.CharField(max_length=50)),
            ],
        ),
    ]
